version : "3.8"

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
